#!/usr/bin/env python3
"""
Train DPS Layer on strg-llm-stk consciousness unlock pack.

Trains DPSGatingLayer on novelty detection and depth unlock:

Novelty Weight: NW = V x I x (1 - S)
    V = validity (verifier confidence x consistency x evidence)
    I = impact (reward gain, cost reduction, uncertainty drop)
    S = similarity to existing knowledge

Classifications:
    HEAVY (NW >= 0.70): Immediate unlock
    COUNT (0.45 <= NW < 0.70): Token accumulation
    NOCOUNT (NW < 0.45): No progress

Training Objectives:
1. Compute novelty weight from V, I, S components
2. Classify as HEAVY/COUNT/NOCOUNT
3. Update DPS state (p_max, tokens, cooldown)
4. Respect high-stakes mode constraints

Usage:
    python scripts/train_dps_layer.py --epochs 10 --batch-size 32

Data:
    - strg-llm-stk/tks_consciousness_unlock_HS_enabled_pack_1000.jsonl

Author: ML Agent
Date: 2026-01-05
"""

import argparse
import json
import logging
import os
import re
import sys
from pathlib import Path
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR

# =============================================================================
# GPU ENFORCEMENT - Training requires CUDA
# =============================================================================

def enforce_gpu():
    """Enforce GPU usage - refuse to train on CPU."""
    if not torch.cuda.is_available():
        print("\n" + "=" * 60)
        print("ERROR: CUDA GPU NOT AVAILABLE")
        print("=" * 60)
        print("This training script requires a CUDA-capable GPU.")
        print("CPU training is disabled to prevent:")
        print("  - Extremely slow training (10-100x slower)")
        print("  - CPU overheating")
        print("  - Poor resource utilization")
        print("\nTo fix:")
        print("  1. Ensure you have an NVIDIA GPU")
        print("  2. Install CUDA toolkit")
        print("  3. Install PyTorch with CUDA: pip install torch --index-url https://download.pytorch.org/whl/cu118")
        print("=" * 60 + "\n")
        sys.exit(1)

    device = torch.device("cuda")
    gpu_name = torch.cuda.get_device_name(0)
    gpu_memory = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"GPU Enforced: {gpu_name} ({gpu_memory:.1f} GB)")
    return device

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from training.strg_losses import (
    DPSTrainingLoss,
    NoveltyWeightLoss,
    DPSClassificationLoss,
    DPSStateUpdateLoss,
    STRGLossConfig,
)

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


# =============================================================================
# CONFIGURATION
# =============================================================================

@dataclass
class DPSTrainingConfig:
    """Configuration for DPS layer training."""
    # Data - UPDATED: Use synthetic data generated by generate_dps_training_data.py
    data_path: str = "data/dps_training_data.jsonl"
    train_split: float = 0.9

    # Model
    noetic_dim: int = 40
    hidden_dim: int = 64
    validity_dim: int = 32
    impact_dim: int = 32

    # DPS thresholds
    heavy_threshold: float = 0.70
    count_threshold: float = 0.45
    n_tokens_threshold: int = 5
    cooldown_k: int = 10
    max_depth: int = 5

    # Training
    epochs: int = 10
    batch_size: int = 32
    learning_rate: float = 1e-4
    weight_decay: float = 0.01
    warmup_steps: int = 100
    max_grad_norm: float = 1.0

    # Loss weights
    lambda_novelty: float = 1.0
    lambda_classification: float = 1.0
    lambda_state: float = 0.5
    lambda_unlock: float = 0.3

    # Checkpointing
    checkpoint_dir: str = "output/dps_layer"
    save_every: int = 200
    log_every: int = 20

    # Device
    device: str = "auto"


# =============================================================================
# NOVELTY CLASS MAPPING
# =============================================================================

NOVELTY_CLASS_MAP = {
    'HEAVY': 0,
    'COUNT': 1,
    'NOCOUNT': 2,
}


# =============================================================================
# DATASET
# =============================================================================

class DPSDataset(Dataset):
    """Dataset for DPS layer training from consciousness unlock pack."""

    def __init__(
        self,
        data_path: str,
        noetic_dim: int = 40,
        max_samples: Optional[int] = None,
    ):
        self.noetic_dim = noetic_dim
        self.samples = []

        full_path = PROJECT_ROOT / data_path
        if full_path.exists():
            logger.info(f"Loading {full_path}")
            self._load_jsonl(full_path)

        if max_samples:
            self.samples = self.samples[:max_samples]

        logger.info(f"Loaded {len(self.samples)} DPS training samples")

    def _load_jsonl(self, path: Path) -> None:
        """Load samples from JSONL file."""
        with open(path, 'r', encoding='utf-8') as f:
            for line in f:
                try:
                    record = json.loads(line.strip())
                    sample = self._parse_record(record)
                    if sample is not None:
                        self.samples.append(sample)
                except json.JSONDecodeError:
                    continue

    def _parse_record(self, record: Dict) -> Optional[Dict]:
        """Parse a training record into a sample."""
        # NEW FORMAT: Synthetic data from generate_dps_training_data.py
        if 'context_features' in record:
            return self._parse_synthetic_record(record)

        # LEGACY FORMAT: Messages-based format
        messages = record.get('messages', [])

        # Find user and assistant messages
        user_msg = None
        assistant_msg = None
        for msg in messages:
            if msg.get('role') == 'user':
                user_msg = msg.get('content', '')
            elif msg.get('role') == 'assistant':
                assistant_msg = msg.get('content', '')

        if not user_msg or not assistant_msg:
            return None

        # Parse the structured output from assistant
        parsed = self._parse_assistant_output(assistant_msg)
        if parsed is None:
            return None

        # Parse user input for V, I, S components
        vis_components = self._parse_user_input(user_msg)

        return {
            'input_text': user_msg,
            'target_text': assistant_msg,
            **parsed,
            **vis_components,
        }

    def _parse_synthetic_record(self, record: Dict) -> Optional[Dict]:
        """
        Parse synthetic data from generate_dps_training_data.py.

        Expected fields:
        - context_features: List[float] - 40-dim embedding
        - validity, impact, similarity: float
        - novelty_weight: float
        - novelty_class: int (0=HEAVY, 1=COUNT, 2=NOCOUNT)
        - current_p_max, current_tokens, is_in_cooldown
        - should_unlock, next_p_max, next_tokens
        """
        try:
            return {
                # Context embedding (40-dim)
                'embedding': record['context_features'],

                # V, I, S components
                'v': record['validity'],
                'i': record['impact'],
                's': record['similarity'],

                # Target outputs
                'nw': record['novelty_weight'],
                'novelty_class': record['novelty_class'],
                'unlock': 1 if record['should_unlock'] else 0,

                # State info
                'prev_state': {
                    'p_max': record['current_p_max'],
                    'tokens': record['current_tokens'],
                    'cooldown': 10 if record['is_in_cooldown'] else 0,
                },
                'next_state': {
                    'p_max': record['next_p_max'],
                    'tokens': record['next_tokens'],
                    'cooldown': 10 if record['should_unlock'] else 0,
                },

                # Metadata
                'scenario_type': record.get('scenario_type', 'UNKNOWN'),
                'description': record.get('description', ''),
            }
        except KeyError as e:
            logger.warning(f"Missing field in synthetic record: {e}")
            return None

    def _parse_assistant_output(self, text: str) -> Optional[Dict]:
        """
        Parse structured assistant output.

        Expected format:
        NW/Class/Unlock/Reason: 0.XX/HEAVY|COUNT|NOCOUNT/YES|NO/...
        p_max/tokens/cooldown: X → Y / X → Y / X → Y
        """
        result = {}

        # Parse NW and classification
        nw_match = re.search(r'NW[^:]*:\s*([0-9.]+)\s*/\s*(HEAVY|COUNT|NOCOUNT)', text)
        if nw_match:
            result['nw'] = float(nw_match.group(1))
            result['novelty_class'] = NOVELTY_CLASS_MAP.get(nw_match.group(2), 2)
        else:
            return None

        # Parse unlock
        unlock_match = re.search(r'Unlock[^:]*:\s*(YES|NO)', text, re.IGNORECASE)
        if unlock_match:
            result['unlock'] = 1 if unlock_match.group(1).upper() == 'YES' else 0
        else:
            result['unlock'] = 0

        # Parse state transitions
        state_match = re.search(
            r'p_max[^:]*:\s*(\d+)\s*→\s*(\d+).*?'
            r'tokens[^:]*:\s*(\d+)\s*→\s*(\d+).*?'
            r'cooldown[^:]*:\s*(\d+)\s*→\s*(\d+)',
            text, re.IGNORECASE | re.DOTALL
        )
        if state_match:
            result['prev_state'] = {
                'p_max': int(state_match.group(1)),
                'tokens': int(state_match.group(3)),
                'cooldown': int(state_match.group(5)),
            }
            result['next_state'] = {
                'p_max': int(state_match.group(2)),
                'tokens': int(state_match.group(4)),
                'cooldown': int(state_match.group(6)),
            }
        else:
            # Default state
            result['prev_state'] = {'p_max': 2, 'tokens': 0, 'cooldown': 0}
            result['next_state'] = {'p_max': 2, 'tokens': 0, 'cooldown': 0}

        return result

    def _parse_user_input(self, text: str) -> Dict:
        """Parse V, I, S components from user input."""
        result = {}

        # Parse V (validity) - look for patterns like V=0.XX or validity=0.XX
        v_match = re.search(r'[Vv](?:alidity)?\s*[=:]\s*([0-9.]+)', text)
        if v_match:
            result['v'] = float(v_match.group(1))
        else:
            result['v'] = 0.5  # Default

        # Parse I (impact)
        i_match = re.search(r'[Ii](?:mpact)?\s*[=:]\s*([0-9.]+)', text)
        if i_match:
            result['i'] = float(i_match.group(1))
        else:
            result['i'] = 0.5  # Default

        # Parse S (similarity)
        s_match = re.search(r'[Ss](?:imilarity)?\s*[=:]\s*([0-9.]+)', text)
        if s_match:
            result['s'] = float(s_match.group(1))
        else:
            result['s'] = 0.5  # Default

        # Parse high-stakes mode
        result['high_stakes'] = 1 if 'high-stakes' in text.lower() or 'hs' in text.lower() else 0

        return result

    def __len__(self) -> int:
        return len(self.samples)

    def __getitem__(self, idx: int) -> Dict:
        sample = self.samples[idx]

        # Use pre-computed embedding if available (synthetic data)
        if 'embedding' in sample:
            noetic_input = torch.tensor(sample['embedding'], dtype=torch.float32)
        else:
            # Fallback: Generate pseudo-random embeddings from text hash
            text_hash = hash(sample.get('input_text', str(idx))) % (2**32)
            torch.manual_seed(text_hash)
            noetic_input = torch.randn(self.noetic_dim)

        # Handle optional high_stakes field
        high_stakes = sample.get('high_stakes', 0)

        return {
            'noetic_input': noetic_input,
            'nw': torch.tensor(sample['nw'], dtype=torch.float32),
            'v': torch.tensor(sample['v'], dtype=torch.float32),
            'i': torch.tensor(sample['i'], dtype=torch.float32),
            's': torch.tensor(sample['s'], dtype=torch.float32),
            'novelty_class': torch.tensor(sample['novelty_class']),
            'unlock': torch.tensor(sample['unlock']),
            'prev_p_max': torch.tensor(sample['prev_state']['p_max'], dtype=torch.float32),
            'prev_tokens': torch.tensor(sample['prev_state']['tokens'], dtype=torch.float32),
            'prev_cooldown': torch.tensor(sample['prev_state']['cooldown'], dtype=torch.float32),
            'next_p_max': torch.tensor(sample['next_state']['p_max'], dtype=torch.float32),
            'next_tokens': torch.tensor(sample['next_state']['tokens'], dtype=torch.float32),
            'next_cooldown': torch.tensor(sample['next_state']['cooldown'], dtype=torch.float32),
            'high_stakes': torch.tensor(high_stakes),
        }


def collate_fn(batch: List[Dict]) -> Dict:
    """Collate batch of samples."""
    return {
        'noetic_input': torch.stack([s['noetic_input'] for s in batch]),
        'nw': torch.stack([s['nw'] for s in batch]),
        'v': torch.stack([s['v'] for s in batch]),
        'i': torch.stack([s['i'] for s in batch]),
        's': torch.stack([s['s'] for s in batch]),
        'novelty_class': torch.stack([s['novelty_class'] for s in batch]),
        'unlock': torch.stack([s['unlock'] for s in batch]),
        'prev_state': {
            'p_max': torch.stack([s['prev_p_max'] for s in batch]),
            'tokens': torch.stack([s['prev_tokens'] for s in batch]),
            'cooldown': torch.stack([s['prev_cooldown'] for s in batch]),
        },
        'next_state': {
            'p_max': torch.stack([s['next_p_max'] for s in batch]),
            'tokens': torch.stack([s['next_tokens'] for s in batch]),
            'cooldown': torch.stack([s['next_cooldown'] for s in batch]),
        },
        'high_stakes': torch.stack([s['high_stakes'] for s in batch]),
    }


# =============================================================================
# TRAINING LOOP
# =============================================================================

def train_dps_layer(config: DPSTrainingConfig) -> None:
    """Main training loop for DPS layer."""

    # Setup device - GPU ONLY (no CPU training allowed)
    device = enforce_gpu()
    logger.info(f"Using device: {device}")

    # Create output directory
    checkpoint_dir = Path(config.checkpoint_dir)
    checkpoint_dir.mkdir(parents=True, exist_ok=True)

    # Load dataset
    dataset = DPSDataset(config.data_path, noetic_dim=config.noetic_dim)

    # Split train/val
    train_size = int(len(dataset) * config.train_split)
    val_size = len(dataset) - train_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        dataset, [train_size, val_size]
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=config.batch_size,
        shuffle=True,
        collate_fn=collate_fn,
        num_workers=0,
    )
    val_loader = DataLoader(
        val_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        collate_fn=collate_fn,
        num_workers=0,
    )

    logger.info(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}")

    # Load model
    try:
        from tks_features.dps_gating import DPSGatingLayer, DPSConfig
        dps_config = DPSConfig(
            hidden_dim=config.hidden_dim,
            validity_dim=config.validity_dim,
            impact_dim=config.impact_dim,
            heavy_threshold=config.heavy_threshold,
            count_threshold=config.count_threshold,
            n_tokens_threshold=config.n_tokens_threshold,
            cooldown_k=config.cooldown_k,
            max_depth=config.max_depth,
        )
        model = DPSGatingLayer(dps_config, noetic_dim=config.noetic_dim)
    except ImportError:
        logger.warning("DPSGatingLayer not found, using simple model")
        model = SimpleDPSModel(config.noetic_dim, config.hidden_dim)

    model = model.to(device)
    logger.info(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

    # Optimizer and scheduler
    optimizer = AdamW(
        model.parameters(),
        lr=config.learning_rate,
        weight_decay=config.weight_decay,
    )
    scheduler = CosineAnnealingLR(
        optimizer,
        T_max=len(train_loader) * config.epochs,
    )

    # Loss functions
    loss_config = STRGLossConfig(
        lambda_novelty_weight=config.lambda_novelty,
        lambda_classification=config.lambda_classification,
        lambda_state_update=config.lambda_state,
    )
    dps_loss_fn = DPSTrainingLoss(
        config=loss_config,
        heavy_threshold=config.heavy_threshold,
        count_threshold=config.count_threshold,
    )

    # Training loop
    global_step = 0
    best_val_loss = float('inf')

    for epoch in range(config.epochs):
        model.train()
        epoch_loss = 0.0
        epoch_steps = 0
        epoch_accuracy = 0.0

        for batch_idx, batch in enumerate(train_loader):
            # Move to device
            noetic_input = batch['noetic_input'].to(device)
            target_nw = batch['nw'].to(device)
            target_v = batch['v'].to(device)
            target_i = batch['i'].to(device)
            target_s = batch['s'].to(device)
            target_class = batch['novelty_class'].to(device)
            target_unlock = batch['unlock'].to(device)
            next_state = {k: v.to(device) for k, v in batch['next_state'].items()}

            # Forward pass
            optimizer.zero_grad()

            if hasattr(model, 'compute_novelty_batch'):
                # DPSGatingLayer with batch-compatible training method
                output = model.compute_novelty_batch(noetic_input.unsqueeze(1))

                predictions = {
                    'novelty': {
                        'nw': output['nw'],
                        'v': output['v'],
                        'i': output['i'],
                        's': output['s'],
                    },
                    'class_logits': output['class_logits'],
                    'unlock_logit': torch.zeros_like(target_unlock.float()),
                    'next_state': next_state,
                }
            elif hasattr(model, 'compute_novelty'):
                # Legacy DPSGatingLayer path (scalar output - will fail with batch loss)
                novelty = model.compute_novelty(noetic_input.unsqueeze(1))

                predictions = {
                    'novelty': {
                        'nw': torch.tensor([novelty.value] * len(target_nw), device=device),
                        'v': torch.tensor([novelty.validity.value] * len(target_nw), device=device),
                        'i': torch.tensor([novelty.impact.value] * len(target_nw), device=device),
                        's': torch.tensor([novelty.similarity.value] * len(target_nw), device=device),
                    },
                    'class_logits': torch.zeros(len(target_nw), 3, device=device),
                    'unlock_logit': torch.zeros_like(target_unlock.float()),
                    'next_state': next_state,
                }
            elif hasattr(model, 'forward_training'):
                output = model.forward_training(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': output.get('nw', output.get('novelty_weight', torch.zeros_like(target_nw))),
                        'v': output.get('v', torch.zeros_like(target_v)),
                        'i': output.get('i', torch.zeros_like(target_i)),
                        's': output.get('s', torch.zeros_like(target_s)),
                    },
                    'class_logits': output.get('class_logits', torch.zeros(len(target_nw), 3, device=device)),
                    'next_state': output.get('next_state', next_state),
                    'unlock_logit': output.get('unlock_logit', torch.zeros_like(target_unlock.float())),
                }
            else:
                output = model(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': output.get('nw', output.get('novelty_weight', torch.zeros_like(target_nw))),
                        'v': output.get('v', torch.zeros_like(target_v)),
                        'i': output.get('i', torch.zeros_like(target_i)),
                        's': output.get('s', torch.zeros_like(target_s)),
                    },
                    'class_logits': output.get('class_logits', torch.zeros(len(target_nw), 3, device=device)),
                    'next_state': output.get('next_state', next_state),
                    'unlock_logit': output.get('unlock_logit', torch.zeros_like(target_unlock.float())),
                }

            # Prepare targets dict
            targets = {
                'nw': target_nw,
                'v': target_v,
                'i': target_i,
                's': target_s,
                'novelty_class': target_class,
                'unlock': target_unlock,
                'next_state': next_state,
            }

            # Compute loss
            loss_dict = dps_loss_fn(predictions, targets)
            total_loss = loss_dict['total']

            # Backward pass
            total_loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), config.max_grad_norm)
            optimizer.step()
            scheduler.step()

            epoch_loss += total_loss.item()
            epoch_steps += 1
            global_step += 1

            if 'classification_accuracy' in loss_dict:
                epoch_accuracy += loss_dict['classification_accuracy'].item()

            # Logging
            if global_step % config.log_every == 0:
                avg_loss = epoch_loss / epoch_steps
                avg_acc = epoch_accuracy / epoch_steps
                lr = scheduler.get_last_lr()[0]
                logger.info(
                    f"Step {global_step} | Epoch {epoch+1}/{config.epochs} | "
                    f"Loss: {avg_loss:.4f} | Acc: {avg_acc:.4f} | LR: {lr:.2e}"
                )

            # Checkpointing
            if global_step % config.save_every == 0:
                save_checkpoint(
                    model, optimizer, scheduler, global_step, epoch,
                    checkpoint_dir / f"step_{global_step}.pt"
                )

        # End of epoch
        avg_epoch_loss = epoch_loss / max(epoch_steps, 1)
        avg_epoch_acc = epoch_accuracy / max(epoch_steps, 1)
        logger.info(f"Epoch {epoch+1} complete. Avg loss: {avg_epoch_loss:.4f}, Avg acc: {avg_epoch_acc:.4f}")

        # Validation
        val_loss, val_acc = validate(model, val_loader, device, dps_loss_fn)
        logger.info(f"Validation loss: {val_loss:.4f}, acc: {val_acc:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            save_checkpoint(
                model, optimizer, scheduler, global_step, epoch,
                checkpoint_dir / "best.pt"
            )
            logger.info(f"New best model saved (val_loss: {val_loss:.4f})")

    # Save final model
    save_checkpoint(
        model, optimizer, scheduler, global_step, epoch,
        checkpoint_dir / "final.pt"
    )
    logger.info("Training complete!")

    # Export pretrained weights
    torch.save(model.state_dict(), checkpoint_dir / "dps_layer_pretrained.pt")
    logger.info(f"Exported pretrained weights to {checkpoint_dir / 'dps_layer_pretrained.pt'}")


def validate(model, val_loader, device, loss_fn) -> Tuple[float, float]:
    """Run validation."""
    model.eval()
    total_loss = 0.0
    total_acc = 0.0
    num_batches = 0

    with torch.no_grad():
        for batch in val_loader:
            noetic_input = batch['noetic_input'].to(device)
            target_nw = batch['nw'].to(device)
            target_class = batch['novelty_class'].to(device)
            next_state = {k: v.to(device) for k, v in batch['next_state'].items()}

            if hasattr(model, 'compute_novelty_batch'):
                output = model.compute_novelty_batch(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': output['nw'],
                    },
                    'class_logits': output['class_logits'],
                    'next_state': next_state,
                }
            elif hasattr(model, 'compute_novelty'):
                novelty = model.compute_novelty(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': torch.tensor([novelty.value] * len(target_nw), device=device),
                    },
                    'class_logits': torch.zeros(len(target_nw), 3, device=device),
                    'next_state': next_state,
                }
            elif hasattr(model, 'forward_training'):
                output = model.forward_training(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': output.get('nw', output.get('novelty_weight', torch.zeros_like(target_nw))),
                    },
                    'class_logits': output.get('class_logits', torch.zeros(len(target_nw), 3, device=device)),
                    'next_state': output.get('next_state', next_state),
                }
            else:
                output = model(noetic_input.unsqueeze(1))
                predictions = {
                    'novelty': {
                        'nw': output.get('nw', output.get('novelty_weight', torch.zeros_like(target_nw))),
                    },
                    'class_logits': output.get('class_logits', torch.zeros(len(target_nw), 3, device=device)),
                    'next_state': output.get('next_state', next_state),
                }

            targets = {
                'nw': target_nw,
                'novelty_class': target_class,
                'next_state': next_state,
            }

            loss_dict = loss_fn(predictions, targets)
            total_loss += loss_dict['total'].item()

            if 'classification_accuracy' in loss_dict:
                total_acc += loss_dict['classification_accuracy'].item()

            num_batches += 1

    return total_loss / max(num_batches, 1), total_acc / max(num_batches, 1)


def save_checkpoint(
    model, optimizer, scheduler, step, epoch, path: Path
) -> None:
    """Save training checkpoint."""
    torch.save({
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'scheduler_state_dict': scheduler.state_dict(),
        'step': step,
        'epoch': epoch,
    }, path)


class SimpleDPSModel(nn.Module):
    """Simple fallback model if DPSGatingLayer unavailable."""

    def __init__(self, noetic_dim: int = 40, hidden_dim: int = 64):
        super().__init__()
        self.noetic_dim = noetic_dim

        # V/I/S computation networks
        self.validity_net = nn.Sequential(
            nn.Linear(noetic_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid(),
        )

        self.impact_net = nn.Sequential(
            nn.Linear(noetic_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid(),
        )

        self.similarity_net = nn.Sequential(
            nn.Linear(noetic_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid(),
        )

        # Classification head
        self.classifier = nn.Linear(noetic_dim + 3, 3)

        # Unlock prediction
        self.unlock_head = nn.Linear(noetic_dim + 3, 1)

        # State prediction
        self.state_head = nn.Linear(noetic_dim + 3, 3)  # p_max, tokens, cooldown

    def forward(self, x: torch.Tensor) -> Dict[str, torch.Tensor]:
        batch_size = x.shape[0]
        if x.dim() == 3:
            x = x.squeeze(1)  # [batch, dim]

        # Compute V, I, S
        v = self.validity_net(x).squeeze(-1)
        i = self.impact_net(x).squeeze(-1)
        s = self.similarity_net(x).squeeze(-1)

        # Compute NW = V x I x (1 - S)
        nw = v * i * (1 - s)

        # Features for classification
        features = torch.cat([x, v.unsqueeze(-1), i.unsqueeze(-1), s.unsqueeze(-1)], dim=-1)

        # Classification logits
        class_logits = self.classifier(features)

        # Unlock logit
        unlock_logit = self.unlock_head(features).squeeze(-1)

        # State prediction
        state_pred = self.state_head(features)

        return {
            'nw': nw,
            'novelty_weight': nw,
            'v': v,
            'i': i,
            's': s,
            'class_logits': class_logits,
            'unlock_logit': unlock_logit,
            'next_state': {
                'p_max': state_pred[:, 0] * 5,  # Scale to [0, 5]
                'tokens': state_pred[:, 1] * 5,  # Scale to [0, 5]
                'cooldown': state_pred[:, 2] * 10,  # Scale to [0, 10]
            },
        }


# =============================================================================
# MAIN
# =============================================================================

def main():
    parser = argparse.ArgumentParser(description="Train DPS Layer")
    parser.add_argument("--epochs", type=int, default=10)
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--device", type=str, default="auto")
    parser.add_argument("--checkpoint-dir", type=str, default="output/dps_layer")
    args = parser.parse_args()

    config = DPSTrainingConfig(
        epochs=args.epochs,
        batch_size=args.batch_size,
        learning_rate=args.lr,
        device=args.device,
        checkpoint_dir=args.checkpoint_dir,
    )

    train_dps_layer(config)


if __name__ == "__main__":
    main()
